name: components
version: 3.0.2
author: Clean Team <clean@vacuumlabs.com>
description: Simple components for React
homepage: https://github.com/cleandart/components
dependencies:
  browser: '>=0.9.1 <0.11.0'
  clean_data: '>=0.4.13 <0.5.0'
  intl: '>=0.9.7 <0.10.0'
  logging: '>=0.9.1 <0.10.0'
  mock: any
  quiver: any
  react: '>=0.4.0 <0.5.0'
dev_dependencies:
  clean_backend: '>=0.5.2 <0.6.0'
  clean_sync: '>=0.3.10 <0.4.0'
  js: '>=0.2.2 <0.3.0'
  unittest: any
