name: components
version: 2.0.0
author: Clean Team <clean@vacuumlabs.com>
description: Simple components for React
homepage: https://github.com/cleandart/components
dependencies:
  browser: '>=0.9.1 <0.11.0'
  clean_data: '>=0.4.0 <0.5.0'
  intl: '>=0.9.7 <0.10.0'
  logging: '>=0.9.1 <0.10.0'
  react: '>=0.3.5 <0.4.0'
dev_dependencies:
  clean_backend: '>=0.2.1 <0.3.0'
  clean_sync: '>=0.3.10 <0.4.0'
  js: '>=0.2.2 <0.3.0'
  unittest: any
