name: components
version: 1.2.1
author: Clean Team <clean@vacuumlabs.com>
description: Simple components for React
homepage: https://github.com/cleandart/components
dependencies:
  browser: '>=0.9.1 <0.9.2'
  clean_data: '>=0.3.8'
  intl: any
  logging: any
  react: '>=0.3.0'
dev_dependencies:
  clean_backend: '>=0.2.1 <0.3.0'
  clean_sync: '>=0.3.10 <0.4.0'
  js: '>=0.2.2 <0.3.0'
  unittest: any
