name: components
version: 1.0.7
description: A sample web application
dependencies:
  browser: any
  clean_backend: any
  clean_data: '>=0.3.8'
  clean_sync: any
  intl: any
  js: any
  logging: any
  react: '>=0.3.0'
  unittest: any
