name: components
author: Clean Team <clean@vacuumlabs.com>
version: 1.1.1
homepage: https://github.com/cleandart/components
description: Simple components for React
dependencies:
  browser: '>=0.9.1 <0.9.2'
  clean_backend: '>=0.2.1 <0.3.0'
  clean_data: '>=0.3.8'
  clean_sync: '>=0.3.10 <0.4.0'
  intl: '>=0.9.7 <0.10.0'
  js: '>=0.2.2 <0.3.0'
  logging: '>=0.9.1+1 <0.10.0'
  react: '>=0.3.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
